@InnoCheffing.API_HostAddress = https://localhost:7218

GET {{InnoCheffing.API_HostAddress}}/api/ingredients?pageNumber=2&pageSize=1
Accept: application/json
###

GET {{InnoCheffing.API_HostAddress}}/api/ingredients/2e1554fe-2f75-4330-baaf-663ad055bc89
Accept: application/json
###

POST {{InnoCheffing.API_HostAddress}}/api/ingredients/
Content-Type: application/json

{
  "name": "Orange"
}
###

PUT {{InnoCheffing.API_HostAddress}}/api/ingredients/2e1554fe-2f75-4330-baaf-663ad055bc89
Content-Type: application/json

{
  "name": "UPDATED Orange"
}
###

DELETE {{InnoCheffing.API_HostAddress}}/api/ingredients/2e1554fe-2f75-4330-baaf-663ad055bc89
###
