@InnoCheffing.API_HostAddress = https://localhost:7218


GET {{InnoCheffing.API_HostAddress}}/api/ingredients/?pageNumber=1&pageSize=20
Accept: application/json
###

GET {{InnoCheffing.API_HostAddress}}/api/ingredients/ed5a9e35-d6fb-4b17-b140-6863aad057ef
Accept: application/json
###

POST {{InnoCheffing.API_HostAddress}}/api/ingredients/
Content-Type: application/json

{
  "name": ""
}
###

PUT {{InnoCheffing.API_HostAddress}}/api/ingredients/ed5a9e35-d6fb-4b17-b140-6863aad057ef
Content-Type: application/json

{
}
###

DELETE {{InnoCheffing.API_HostAddress}}/api/ingredients/ed5a9e35-d6fb-4b17-b140-6863aad057ef
###

GET {{InnoCheffing.API_HostAddress}}/api/recipecategories/
Accept: application/json
###

GET {{InnoCheffing.API_HostAddress}}/api/recipecategories/c09a7130-b733-49ce-9528-743c2d200046
Accept: application/json
###


POST {{InnoCheffing.API_HostAddress}}/api/recipecategories/
Content-Type: application/json

{
  "name": "Dinner"
}
###

PUT {{InnoCheffing.API_HostAddress}}/api/recipecategories/3c519871-3e05-4bd2-8f33-5ed69451d36f
Content-Type: application/json

{
  "name": "UPDATED Breakfast"
}
###

DELETE {{InnoCheffing.API_HostAddress}}/api/recipecategories/197ad14e-70b3-41e1-a674-cc74cab5249a
###


GET {{InnoCheffing.API_HostAddress}}/api/recipes/?pageNumber=1&pageSize=0
Accept: application/json
###

GET {{InnoCheffing.API_HostAddress}}/api/recipes/70b1fcc8-88fc-41b0-a490-06d018854d7b
Accept: application/json
###

POST {{InnoCheffing.API_HostAddress}}/api/recipes/
Content-Type: application/json

{
  "name": "test",
  "recipeCategoryId": "70b1fcc8-88fc-41b0-a490-06d01885"
}
###

PUT {{InnoCheffing.API_HostAddress}}/api/recipes/70b1fcc8-88fc-41b0-a490-06d018854d7b
Content-Type: application/json

{
  "name": "UPDATED 3 Spaghetti 3",
}
###

DELETE {{InnoCheffing.API_HostAddress}}/api/recipes/
###